---
- name: Install nginx
  ansible.builtin.include_role:
    name: nginxinc.nginx
- name: Deploy config file
  ansible.builtin.template:
    src: etc/nginx/conf.d/web.conf.j2
    dest: /etc/nginx/conf.d/web.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Reload nginx
