---
- name: Create group
  ansible.builtin.group:
    name: "{{ wikijs_group }}"
    state: present
  become: true
- name: Create user
  ansible.builtin.user:
    name: "{{ wikijs_user }}"
    group: "{{ wikijs_group }}"
    comment: wikijs user
    create_home: false
    shell: /sbin/nologin
    state: present
  become: true
- name: Create wikijs directory
  ansible.builtin.file:
    path: "{{ wikijs_dir }}"
    state: directory
    mode: "0744"
    owner: "{{ wikijs_user }}"
    group: "{{ wikijs_group }}"
  become: true
- name: Download wikijs
  ansible.builtin.unarchive:
    src: https://github.com/requarks/wiki/releases/latest/download/wiki-js.tar.gz
    dest: "{{ wikijs_dir }}"
    remote_src: true
    owner: "{{ wikijs_user }}"
    group: "{{ wikijs_group }}"
  become: true
- name: Deploy config file
  ansible.builtin.template:
    src: usr/local/share/wikijs/config.yml.j2
    dest: /usr/local/share/wikijs/config.yml
    owner: "{{ wikijs_user }}"
    group: "{{ wikijs_group }}"
    mode: "0600"
  become: true
- name: Deploy systemd unit file
  ansible.builtin.template:
    src: etc/systemd/system/wikijs.service.j2
    dest: /etc/systemd/system/wikijs.service
    owner: root
    group: root
    mode: "0644"
  become: true
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true
- name: Start wikijs service
  ansible.builtin.systemd:
    name: wikijs
    state: started
    enabled: true
  become: true
