---
- name: Install Kubernetes
  ansible.builtin.import_playbook: kubernetes_sigs.kubespray.cluster
  vars:
    kube_version: v1.30.4
    kube_network_plugin: flannel
    kubeconfig_localhost: true
    kubectl_localhost: true
    helm_enabled: true
    metrics_server_enabled: true
    cert_manager_enabled: true
    # Enable Argo CD addon
    argocd_enabled: true
    kube_proxy_strict_arp: true
    metallb_enabled: true
    metallb_speaker_enabled: true
    metallb_namespace: metallb-system
    metallb_config:
      address_pools:
        primary:
          ip_range:
            - 172.16.200.1-172.16.200.254
          auto_assign: true
      layer2:
        - primary
    ingress_nginx_enabled: true
    ingress_nginx_namespace: ingress-nginx
    ingress_nginx_termination_grace_period_seconds: 300
    ingress_nginx_class: nginx
    ingress_nginx_service_type: LoadBalancer
    ingress_nginx_configmap:
      map-hash-bucket-size: "128"
      ssl-protocols: "TLSv1.2 TLSv1.3"
- name: Install fluent-bit
  hosts: kube_control_plane
  tasks:
    - name: Add fluent chart repo
      kubernetes.core.helm_repository:
        name: fluent
        repo_url: https://fluent.github.io/helm-charts
    - name: Deploy fluent-bit
      kubernetes.core.helm:
        name: fluent-bit
        chart_ref: fluent/fluent-bit
        chart_version: 0.48.3
        namespace: kube-system
        state: present
        values:
          config:
            filters: |
              [FILTER]
                  Name kubernetes
                  Match kube.*
                  Merge_Log On
                  Keep_Log Off
                  K8S-Logging.Parser On
                  K8S-Logging.Exclude On

              [FILTER]
                  Name nest
                  Match kube.*
                  Operation lift
                  Nest_under kubernetes
            outputs: |
              [OUTPUT]
                  name syslog
                  match kube.*
                  host 172.16.100.1
                  port 514
                  mode udp
                  syslog_message_key log
                  syslog_hostname_key namespace_name
                  syslog_appname_key pod_name
                  syslog_procid_key container_name

              [OUTPUT]
                  name syslog
                  match host.*
                  host 172.16.100.1
                  port 514
                  mode udp
                  syslog_message_key log